# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build pre-render
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8

    - name: Install dependencies
      run: npm ci

    - name: build prerender
      run: npm run prerender

    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
        path: dist

  deploy:
    name: Deploy to Amazon S3
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync deploy_dist/geek-in-u/browser s3://${{ secrets.BUCKET_NAME }}
